### PR TITLE
Fix escapes decoding in toJSON

### LINKED ISSUE #1180: Escaping not decoded during toJSON conversion
When escaped string is encountered by native JSON parser (f.e. `"some \"inner\" qoutes and\ttabs"`), it is then stored in the resulting value without backslashes, with special sequences decoded (`some "inner" qoutes and	tabs`).

Because this library focuses on preserving original contents of nodes in the ast tree, it stores the values of strings in their original, escaped form (i.e. `some \"inner\" qoutes and\ttabs`)

As a consequence, when resulting ast tree is converted to json object with `toJSON` helper, the string values then contain escaped source strings, instead of decoded values:

```js
const doubleEscaped = JSON.stringify({ 'a\"\t\"c': 'a\"\t\"c' }); // {"a\"\t\"c":"a\"\t\"c"}

// native parse
const parsed = JSON.parse(doubleEscaped); // { 'a" "c': 'a" "c' } <- space between quotes here is actually a tabulation character

// toJSON
const jsoned = toJSON(parse(doubleEscaped)); // { 'a\"\t\"c': 'a\"\t\"c' } <- \t here is a '\' 't' characters sequence, not the tabulation character itself
```

### PR DESCRIPTION
**Pull request by ankhzet**
Closes #1180 

May be worth noting: i've change the build target for the esm build from `es5` to `es6`, as environments, that support ESM by default either also support `es6` (nodejs, modern-ish browsers with ESM support etc.), or would be consuming the library through an additional transpilation step (namely, Internet Explorer 11). Feel free to revert the change, it is not critical to the PR, just optimizes the esm build by _a lot_

### CODE REVIEW

File: src/ast.ts [hunk 1]
```diff
@@ -82,13 +82,13 @@ export class JsonValue extends JsonNode implements IJsonValue {
...
 
-  constructor(public value: string = null) {
+  constructor(public value: string = null, public decoded: string = null, ) {
     super();
   }
 }
 
 export class JsonComment extends JsonNode implements IJsonValue {
-  public readonly type: JsonNodeTypes.KEY = JsonNodeTypes.KEY;
+  public readonly type: JsonNodeTypes.COMMENT = JsonNodeTypes.COMMENT;
```
Comment (anchan828) [inline src/ast.ts:91]: good catch!🤩

File: src/tokenize.ts [hunk 2]
```diff
@@ -48,6 +33,15 @@ const stringStates = {
...
 
+const symbolSubstitutes = {
+  b: '\b', // Backspace
+  f: '\f', // Form feed
+  n: '\n', // New line
+  r: '\r', // Carriage return
+  t: '\t', // Horizontal tab
+};
+
+// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#escape_sequences
```
Comment (anchan828) [inline src/tokenize.ts:44]: 👍

File: src/ast.ts [hunk 3]
```diff
@@ -82,13 +82,13 @@ export class JsonValue extends JsonNode implements IJsonValue {
 export class JsonKey extends JsonNode implements IJsonValue {
   public readonly type: JsonNodeTypes.KEY = JsonNodeTypes.KEY;
 
-  constructor(public value: string = null) {
+  constructor(public value: string = null, public decoded: string = null, ) {
```
Comment (anchan828) [inline src/ast.ts:85]: small fix 🙏 
```suggestion
  constructor(public value: string = null, public decoded: string = null) {
```

File: src/tokenize.ts [hunk 4]
```diff
@@ -1,27 +1,12 @@
...
-  FALSE = "FALSE", // false
-  NULL = "NULL", // null
-  IDENTIFIER = "IDENTIFIER", // identifiers
-}
+import { JsonToken, JsonTokenTypes, ParseSettings } from "./types.js";
 
 interface ParseJsonToken {
   type: JsonTokenTypes;
   value: string;
+  decoded?: string;
```
Comment (anchan828) [inline src/tokenize.ts:9]: Would it be like this if made more specific with types?
```suggestion
  decoded?: string | null;
```

File: src/types.ts [hunk 5]
```diff
@@ -11,7 +28,8 @@ export interface ParseSettings {
 }
 
 export interface JsonToken {
-  type: any;
-  value: any;
+  type: JsonTokenTypes;
+  value: string;
+  decoded?: string;
```
Comment (anchan828) [inline src/types.ts:33]: Would it be like this if made more specific with types?
```suggestion
  decoded?: string | null;
```

**Review by anchan828 — CHANGES_REQUESTED** [review]
This is brilliant PR! I made a comment because there were a few things I wanted to check.

**Review by anchan828 — APPROVED** [review]
awesome!
